name: Lint and Format Code

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      id: prettier
      run: npx prettier --check .

    - name: Run ESLint
      id: eslint
      run: npx eslint .

    - name: Check for Prettier and ESLint errors
      if: failure()
      run: exit 1

    - name: Annotate ESLint and Prettier errors
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { context, github } = require('@actions/github');
          const { owner, repo, number: pull_number } = context.issue;

          const prettierOutput = await github.actions.listWorkflowRunArtifacts({
            owner,
            repo,
            run_id: context.runId
          });
          const eslintOutput = await github.actions.listWorkflowRunArtifacts({
            owner,
            repo,
            run_id: context.runId
          });

          let commentBody = '';

          if (prettierOutput.artifacts.length > 0) {
            commentBody += '### :x: Prettier check failed\n';
            commentBody += 'Please fix the formatting issues and update the pull request.\n\n';
          }

          if (eslintOutput.artifacts.length > 0) {
            commentBody += '### :x: ESLint check failed\n';
            commentBody += 'Please fix the linting issues and update the pull request.\n\n';
          }

          if (commentBody !== '') {
            await github.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: commentBody
            });
          }
          
